# Generated by Django 3.1.7 on 2021-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imageFile', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
